name: iOS starter workflow

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          xcodebuild clean build -scheme WordFlip -sdk iphonesimulator -destination 'platform=iOS,id=dvtdevice-DVTiPhonePlaceholder-iphoneos:17.0,name=Any iOS Device' 
